### ISSUE TITLE
Release time

### ISSUE THREAD

**Issue by YanzhongSu** [Zhaoxiangyun/Multi-Task-Modulation-Module#1]
Hi Zhao,

I've read your paper, and found it to be very innovative and useful. I am interested in how exactly you and your team implemented this proposal. I appreciate if could you tell us a bit about the **timeline** of when your team is going to release the code. Thank you!

**Comment by Zhaoxiangyun** [comment]
Thanks a lot for your interest.! The code release is still in preparation and will be released soon.  I am so sorry about the delay because I am doing another summer internship outside. I will let you know when it is ready.

**Comment by godlin-bd** [comment]
Hi,Dr.Zhao
I've read your paper and I'm a senior student in China.I'm very admire the excellent results in your paper.But because the limitation of my own knowledge,when I read again and again,I can't make sense that the detail of modulation module,so I can't implement your paper through the code.I appreciate if you could tell us more details of the network framework and modulation module to help us implement in code. For example,how we can learn weights with respect to each task?(in page 7)I am very appreciated that  if you could tell me your email because I have some more specific questions.Thanks a lot!

**Comment by Zhaoxiangyun** [comment]
> Hi,Dr.Zhao
> I've read your paper and I'm a senior student in China.I'm very admire the excellent results in your paper.But because the limitation of my own knowledge,when I read again and again,I can't make sense that the detail of modulation module,so I can't implement your paper through the code.I appreciate if you could tell us more details of the network framework and modulation module to help us implement in code. For example,how we can learn weights with respect to each task?(in page 7)I am very appreciated that if you could tell me your email because I have some more specific questions.Thanks a lot!



> Hi,Dr.Zhao
> I've read your paper and I'm a senior student in China.I'm very admire the excellent results in your paper.But because the limitation of my own knowledge,when I read again and again,I can't make sense that the detail of modulation module,so I can't implement your paper through the code.I appreciate if you could tell us more details of the network framework and modulation module to help us implement in code. For example,how we can learn weights with respect to each task?(in page 7)I am very appreciated that if you could tell me your email because I have some more specific questions.Thanks a lot!



> Hi,Dr.Zhao
> I've read your paper and I'm a senior student in China.I'm very admire the excellent results in your paper.But because the limitation of my own knowledge,when I read again and again,I can't make sense that the detail of modulation module,so I can't implement your paper through the code.I appreciate if you could tell us more details of the network framework and modulation module to help us implement in code. For example,how we can learn weights with respect to each task?(in page 7)I am very appreciated that if you could tell me your email because I have some more specific questions.Thanks a lot!

I am sorry for the late release. The code will be released after CVPR deadline.  In tensorflow, you could define some variables which are learnable. You could have a try.

**Comment by godlin-bd** [comment]
Dr.Zhao
Thank you for your suggestion!
Best wishes.

At 2018-10-30 23:57:28, "Zhaoxiangyun" <notifications@github.com> wrote:


Hi,Dr.Zhao
I've read your paper and I'm a senior student in China.I'm very admire the excellent results in your paper.But because the limitation of my own knowledge,when I read again and again,I can't make sense that the detail of modulation module,so I can't implement your paper through the code.I appreciate if you could tell us more details of the network framework and modulation module to help us implement in code. For example,how we can learn weights with respect to each task?(in page 7)I am very appreciated that if you could tell me your email because I have some more specific questions.Thanks a lot!

Hi,Dr.Zhao
I've read your paper and I'm a senior student in China.I'm very admire the excellent results in your paper.But because the limitation of my own knowledge,when I read again and again,I can't make sense that the detail of modulation module,so I can't implement your paper through the code.I appreciate if you could tell us more details of the network framework and modulation module to help us implement in code. For example,how we can learn weights with respect to each task?(in page 7)I am very appreciated that if you could tell me your email because I have some more specific questions.Thanks a lot!

Hi,Dr.Zhao
I've read your paper and I'm a senior student in China.I'm very admire the excellent results in your paper.But because the limitation of my own knowledge,when I read again and again,I can't make sense that the detail of modulation module,so I can't implement your paper through the code.I appreciate if you could tell us more details of the network framework and modulation module to help us implement in code. For example,how we can learn weights with respect to each task?(in page 7)I am very appreciated that if you could tell me your email because I have some more specific questions.Thanks a lot!

I am sorry for the late release. The code will be released after CVPR deadline. In tensorflow, you could define some variables which are learnable. You could have a try.

**Comment by WingEdge777** [comment]
Hi Zhao,
Sorry to bother you. I've read your paper too, found your results very impressive. I‘m doing some multi-task works and wondering your work inspiring a lot. I've read your paper much more than once, but still can't implement it. Since days elapsed after CVPR deadline (according to your reply), would you please release your code right now?  I will be very  very appreciated about it. For now,  I'm urged to know the details about the implementation. Thanks a lot!
